### ISSUE TITLE
[TODO] Get the SQLs for the data view

### ISSUE THREAD

**Issue by awelxtr** [awelxtr/TicketsManager#21]
- [x] Spenditure per month per one supermarket
- [x] Spenditure per month all supermarkets (multibar)
- [x] Spenditure per supermarket total
- [x] Spenditure per product (over time?/ total?)
- [x] Product price evolution over time per supermarket (multiline)
- [x] Cheapest products per supermarket (this shouldn't be a graph but a table)(Product, Super,price, date)
- [x] Product price per supermarket, last data. (Another table)
